{% set version = '0.15' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rtsne
  version: {{ version|replace("-", "_") }}

source:
  fn: Rtsne_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Rtsne_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Rtsne/Rtsne_{{ version }}.tar.gz
  sha256: 56376e4f0a382fad3d3d40e2cb0562224be5265b827622bcd235e8fc63df276c

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - llvm-openmp  # [osx]
  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - r-rcpp
    - llvm-openmp  # [osx]

test:
  commands:
    - $R -e "library('Rtsne')"  # [not win]
    - "\"%R%\" -e \"library('Rtsne')\""  # [win]

about:
  home: https://github.com/jkrijthe/Rtsne
  license: BSD_3_clause
  summary: An R wrapper around the fast T-distributed Stochastic Neighbor Embedding implementation
    by Van der Maaten  (see <https://github.com/lvdmaaten/bhtsne/> for more information
    on the original implementation).
  license_family: BSD

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
