appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: v8EnBmBJN9iUYGHwnZMxr8wgM5ojFJ/5le2urI+yiyTNAIG9I7yemC7azHkxYXzGAAQaJhU3GWTaq0+qx0OitJrDMYQeav9Emihj4NTi7PeJ9iAV4JuKRZQ4pX2/fXurhGJK6hA18cNfmIxVAPv85VD8LQUdH4g+P/HFYXAo9K/SgdCiWygGypA1XkfE81gN/h2NqxcceEVsHofgfOFc1XvJs/sBlxUuJSSW5lNGiR8Y+5CveTOYnZjSX/aGuluoMWW8+d0WoCE7EoTXYQkaDv6fUKBTBq0tNBinftJ1keUGjGqhiY47kJeYZfLG8UQ47eSl/KscMM8d7t2dn56WX9vb5IWVuqOUzdDizWVLEf1hLdx2QJNUj/Zky+l0MLhPPIB8byqa9hPa38SIw076mfw2tHkguV8tA4XkYXq/3GurFilIPmkKfk81gMmd0u0TnOhq1q7jlBkFS8ZPGuWeXggb553eO5GkQutyep0VbPYn8YDtssT00et+tVzZzYes4M71CkDkwWmLVwBhWKBC8xKMAP2emPfaXGI1eKBNN+n/JteGn0w8zvUKzPI7tr05aASbBp9eztiVl7/gMScxO2fqlnPTe8BSneaokNKPHYwqRewsM1q7JtnZ4aimlsnKslr0I18J7ZuOyYiRbD1Rt8JiaF3yBTysgE3FZBvtiZ8=}
