travis:
  secure:
    BINSTAR_TOKEN: OXfaKp06Orh2Vuix4LQsfsfY3egjcdu9SyJ2iIoleARTIQftEKnAiWScX13zj+RE5A5HPXuo3aZxtotQUo0k8CWwbpFLl5J/QiLf0c2Xf8xUIVtBedKUwftn/BNp6cwmsTASvNoaRcZClDqzzNPVo//K3HQO7lrFiLFtv1Kc6yZOlJ16rYGP/fG8/dzrtX5MUd6MC4e78NjMz+WjQkudVP/22O1sdbFzGmATjUlUEyzKtHAZ66g/faMKlp1GlGqQdCdiQ9eKFY29eUJNF4Si24hT4uhFgMlPfhO9L3CJ9oqqB6I0g12nTjtHKUHi2/bBsxzPucgPLTyXpTjEEJFgWTwsKSCnAMQNIP4TYm1QaCn6e2pc447HpYDX92r7man8MbDdkp9EBuk2lUBVCkdcwhVM0T5kVAjrZzNA7X7dmOAA2mWV57ZAySlhBch8e3NN4BLRYbT/5wx6OSmHjUw5ykXRbqEKAvVd2pc2o04SfJuzNUJqeEdxBG4aJ2fzwMy6sle8mg3PS7GacXZ+id+epdoU9Pilmr7ybzdOjzCf6gsjaPN/uOg16tBdtCPLOtFrJm7gHOlHVYeDZKvpxzxCnFauDthBHCBjRIPWPMeiUr0VbGRGcw1PQZNuXQCqtkgTlbYapt2o/0rXvQZ8caglckpSmRUuMzn7gixC+t6Q6ZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
